### ISSUE TITLE
a11y-image-has-alt-attribute と smarthr-ui の BlankImage の組み合わせでエラー

### ISSUE THREAD

**Issue by yamish123** [kufu/eslint-plugin-smarthr#24]
表題の通り
smarthr-ui の `<BlankImage />` に対して以下のエラーが出る

```tsx
<BlankImage />
```

```
画像にはalt属性を指定してください。SVG component の場合、altを属性として受け取れるようにした上で `<svg role="img" aria-label={alt}>` のように指定してください。画像ではない場合、img or image を末尾に持たない名称に変更してください。eslint(smarthr/a11y-image-has-alt-attribute)
```

📝 
`BlankImage` は引数で `title` を受け取り、svg の `<title>` と `aria-label` に設定している
https://github.com/kufu/smarthr-ui/blob/master/src/components/Image/BlankImage.tsx#L27

**Comment by yamish123** [comment]
`BlankImage` の `title` を `alt` という名前で渡せるようにするか、ルール側を直すか

**Comment by AtsushiM** [comment]
こちらもSmartHRLogoと同じくaltを渡せるようにするのが最適かと思っています (ユーザーにとってはLogoと聞いたら画像としか思わないし実質画像なので...)
