### ISSUE TITLE
a11y-clickable-element-has-text と smarthr-ui の SmartHRLogo の組み合わせでエラー

### ISSUE THREAD

**Issue by yamish123** [kufu/eslint-plugin-smarthr#25]
表題の通り
smarthr-ui の `<SmartHRLogo />` をリンクとして扱うとエラーになる

```
a, button要素にはテキストを設定してください。要素内にアイコン、画像のみを設置する場合はSmartHR UIのvisuallyHiddenText、通常のHTML要素にはaltなどの代替テキスト用属性を指定してくださいeslint(smarthr/a11y-clickable-element-has-text)
```

```tsx
<a href="hoge">
  <SmartHRLogo />
</a>
```

📝 
`SmartHRLogo` は引数で `title` を受け取り、`aria-label` に設定している
https://github.com/kufu/smarthr-ui/blob/master/src/components/SmartHRLogo/SmartHRLogo.tsx#L60

**Comment by yamish123** [comment]
SmartHRLogo の title を alt という名前で渡せるようにするか、ルール側を直すか

**Comment by AtsushiM** [comment]
altを渡せるようにするのが最適かと思っています & ruleで SmartHRLogoの場合は未指定OKにするのが良さそうかな...
